version: "3.9"
   
services:
  jsapp:
    container_name: jsapp
    image: jsapp
    build:
      context: js
    ports:
      - "3000:3000"
    environment:
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
      - EXTERNALPORT=3000
    depends_on:
      - db

  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build:
      context: python
    ports:
      - 80:80
    environment:
      - DB_URI=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
  db:
    container_name: db 
    image: postgres:12
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes: 
  pgdata: {}